plugins {
    id 'com.android.application'
}

android {
    namespace 'org.caravel.android'
    compileSdk 35

    defaultConfig {
        applicationId 'org.caravel.android'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "0.4.1"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    dependencies {\n        implementation 'org.apache.commons:commons-compress:1.28.0'\n    }\n\n    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}
